version: '2.1'
services:
  notebook:
    build: .
    container_name: data-jam-notebook
    environment:
      - DATABASE=postgres://postgres:password@postgres:5432/data_jam
      - GOOGLE_MAPS_API_KEY=AIzaSyD_UFF7KBCM-dVdT8jurWbSeANmxeeGhSQ
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan

  postgres:
    image: postgres:9.6
    container_name: data-jam-db
    environment:
      - POSTGRES_DB=data_jam
      - POSTGRES_PASSWORD=password
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres: {}
